### PR TITLE
Add package.json#files

### PR DESCRIPTION
**Pull request by jamiebuilds**

### CODE REVIEW

**Comment by jamiebuilds** [comment]
This was causing Flow errors for consumers otherwise

**Comment by alexreardon** [comment]
Cool! I will merge and publish soon

**Comment by alexreardon** [comment]
Could the same thing be achieved by ignoring the test directory in npmignore?

**Comment by jamiebuilds** [comment]
Using `package.json#files` is generally better than `.npmignore` but yes you could do that

**Comment by alexreardon** [comment]
Given that this repo already uses `.npmignore` I think it would be best to update that one so there is a single source of truth for npm publishing. Thoughts?

**Comment by alexreardon** [comment]
Or remove the npmignore...

**Comment by alexreardon** [comment]
Which way do you think it should go @thejameskyle ?

**Review by alexreardon — APPROVED** [review]

**Pull request merged**
